### ISSUE TITLE
java.lang.IllegalArgumentException: Transfer variant may not be blank

### ISSUE THREAD

**Issue by GameBurrow** [EthanRStokes/Create#10]
### Describe the Bug

We seem to be randomly getting following error in our server (about 1-2 times a day when somebody messes with a contraption), maybe you have idea what could cause this:
```
java.lang.IllegalArgumentException: Transfer variant may not be blank
```

### Reproduction Steps

N/A

### Expected Result

No crash

### Crash Report or Log

Multiple logs here: https://gist.github.com/GameBurrow/f8fad9e423c0e5acbda5d447a46f9919

### Operating System

MC running in Ubuntu docker image

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

appleskin: AppleSkin 2.5.1+mc1.20
architectury: Architectury 9.1.12
athena: Athena 3.1.1
autoconfig1u: Auto Config v1 Updated 3.4.0
badpackets: Bad Packets 0.4.3
balm-fabric: Balm 7.1.4
bcc: BetterCompatibilityChecker 4.0.1
betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
	org_reflections_reflections: reflections 0.10.2
betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.3
betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
bitsandchisels: BitsAndChisels 2.7.3
	stacc: Stacc 1.5.2+boneless2ahhhh
bodiesbodies: Bodies! Bodies! 1.0.1
botarium: Botarium 2.2.1
	team_reborn_energy: Energy 3.0.0
bwncr: Bad Wither No Cookie Reloaded 3.17.0
c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.0
	c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.0
	c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.0
	c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.0
	c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.0
	c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.0
	c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.0
	c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.0
	c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.0
	c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.0
	c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.0
	c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.0
	c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.0
	c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.0
	c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.0
	c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.0
	c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.0
	c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.0
	c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.0
	c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.0
	com_ibm_async_asyncutil: asyncutil 0.1.0
	net_objecthunter_exp4j: exp4j 0.4.8
	org_threadly_threadly: threadly 7.0
cardinal-components: Cardinal Components API 5.2.2
	cardinal-components-base: Cardinal Components API (base) 5.2.2
	cardinal-components-block: Cardinal Components API (blocks) 5.2.2
	cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
	cardinal-components-entity: Cardinal Components API (entities) 5.2.2
	cardinal-components-item: Cardinal Components API (items) 5.2.2
	cardinal-components-level: Cardinal Components API (world saves) 5.2.2
	cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
	cardinal-components-world: Cardinal Components API (worlds) 5.2.2
carpet: Carpet Mod 1.4.112+v230608
carpet-fixes: Carpet Fixes 1.20-1.16.1
	conditional-mixin: conditional mixin 0.3.1
chipped: Chipped 3.0.1
chunkloaders: Chunk Loaders 1.2.8+a
cloth-config: Cloth Config v11 11.1.106
	cloth-basic-math: cloth-basic-math 0.6.1
clumps: Clumps 12.0.0.3
companion: Companion 5.1.0
computercraft: CC: Tweaked 1.108.4
	com_electronwill_night-config_core: core 3.6.7
	com_electronwill_night-config_toml: toml 3.6.7
	com_jcraft_jzlib: jzlib 1.1.3
	io_netty_netty-codec-http: netty-codec-http 4.1.82.Final
	io_netty_netty-codec-socks: netty-codec-socks 4.1.82.Final
	io_netty_netty-handler-proxy: netty-handler-proxy 4.1.82.Final
	org_squiddev_cobalt: Cobalt 0.7.3
convenientnametags: Convenient Name Tags 1.1.0
	omega-config: OmegaConfig 1.4.0+1.20.1
crafttweaker: CraftTweaker 14.0.23
create: Create 0.5.1-d-build.5+mc1.20.1
	com_google_code_findbugs_jsr305: jsr305 3.0.2
	milk: Milk Lib 1.2.60
		dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
	porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
	porting_lib_base: Porting Lib Base 2.1.1127+1.20
		porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
		porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
	porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
	porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
	porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
		porting_lib_core: Porting Lib Core 2.1.1127+1.20
		porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
		porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
	porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
	porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
	porting_lib_models: Porting Lib Models 2.1.1127+1.20
	porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
	porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
		porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
		porting_lib_common: Porting Lib Common 2.1.1127+1.20
		porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
	porting_lib_tags: Porting Lib Tags 3.0
	porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
	porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
	reach-entity-attributes: Reach Entity Attributes 2.4.0
	registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
		porting_lib_data: Porting Lib Data 2.1.1090+1.20
		porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
			porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
create-track-map: Create Track Map 1.4
create_jetpack: Create Jetpack 4.0.0
	flightlib: Flight Lib 2.0.0
create_new_age: Create: New Age 1.1.pre3
create_structures: Create: Structures 1.1.0
createaddition: Create Crafts & Additions 0.9.0
ctov: ChoiceTheorem's Overhauled Village 3.3.6
cupboard: cupboard 1.20.1-2.1
dcintegration-fabric: Discord Integration Fabric 3.0.3
	de_erdbeerbaerlp_dcintegration_common: dcintegration.common 3.0.3
	placeholder-api: Placeholder API 2.1.2+1.20.1
debugify: Debugify 1.20.1+2.0
decorative_blocks: Decorative Blocks 4.0.3
dynmap: Dynmap 3.6
enchanted-vertical-slabs: Enchanted Vertical Slabs 1.9.1
enderman_tweaks: Enderman Tweaks 0.2.0
explorerscompass: Explorer's Compass 1.20.1-2.2.3-fabric
extended_drawers: Extended Drawers 2.0.8+mc.1.20.1
	config_toolkit: ConfigToolkit 1.0.0
		io_determann_shadow-api-17: shadow-api-17 0.1.1
		net_fabricmc_javapoet: javapoet 0.1.0
	graphlib: Graph Lib 1.4.0+1.20
		libnetworkstack: Lib Network Stack 0.10.0
fabric-api: Fabric API 0.90.7+1.20.1
	fabric-api-base: Fabric API Base 0.4.30+7abfd51577
	fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
	fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
	fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
	fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
	fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
	fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
	fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
	fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
	fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
	fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
	fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
	fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.2+d7b148e077
	fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
	fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
	fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
	fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
	fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
	fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
	fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
	fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
	fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
	fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
	fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
	fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
	fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
	fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
	fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
	fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
	fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
	fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
	fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
	fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
	fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.6+d7b148e077
	fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
	fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
	fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.2+1bc31aeb77
	fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
fabric-language-kotlin: Fabric Language Kotlin 1.10.13+kotlin.1.9.20
	org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.20
	org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.20
	org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.20
	org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.20
	org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.22.0
	org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
	org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
	org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.1
	org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.0
	org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.0
	org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.0
fabricloader: Fabric Loader 0.14.24
fallingtree: FallingTree 4.3.1
faux-custom-entity-data: Faux-Custom-Entity-Data 6.0.1
ferritecore: FerriteCore 6.0.1
forgeconfigapiport: Forge Config API Port 8.0.0
fusion: Fusion 1.1.0+a
geckolib: GeckoLib 4 4.2.4
	com_eliotlash_mclib_mclib: mclib 20
gottagofast: Gotta Go Fast! 1.1.0
immersive_paintings: Immersive Paintings 0.6.7+1.20.1
inventoryessentials: Inventory Essentials 8.2.1
inventorysorter: Inventory Sorter 1.9.0-1.20
	kyrptconfig: Kyrpt Config 1.5.6-1.20
jade: Jade 11.6.2
jadeaddons: Jade Addons 5.2.3
jamlib: JamLib 0.6.1+1.20.x
java: OpenJDK 64-Bit Server VM 21
krypton: Krypton 0.2.3
	com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
lazydfu: LazyDFU 0.1.3
lithium: Lithium 0.11.2
magnumtorch: Magnum Torch 8.0.0
mcwbridges: Macaw's Bridges 2.1.0
mcwdoors: Macaw's Doors 1.1.0
mcwfences: Macaw's Fences and Walls 1.0.7
mcwwindows: Macaw's Windows 2.2.0
memoryleakfix: Memory Leak Fix 1.1.2
midnightlib: MidnightLib 1.4.1
minecraft: Minecraft 1.20.1
modernfix: ModernFix 5.9.2+mc1.20.1
moonlight: Moonlight 1.20-2.8.60
mr_ctov_createstructures: CTOV - Create: Structures 1.0
naturalist: Naturalist 4.0.3
naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
niftycarts: NiftyCarts 3.0.0+1.20.1
nochatreports: No Chat Reports 1.20.1-v2.2.2
owo: oωo 0.11.2+1.20
	blue_endless_jankson: jankson 1.2.2
patchouli: Patchouli 1.20.1-81-FABRIC
	fiber: fiber 0.23.0-2
pfm: Paladin's Furniture 1.2.0
pickupnotifier: Pick Up Notifier 8.0.0
polymorph: Polymorph 0.49.1+1.20.1
	spectrelib: SpectreLib 0.13.14+1.20.1
puzzleslib: Puzzles Lib 8.1.8
	puzzlesaccessapi: Puzzles Access Api 8.0.7
railways: Create: Steam 'n' Rails 1.5.1+fabric-mc1.20.1
	mm: Manningham Mills 2.3
resourcefullib: Resourceful Lib 2.1.16
	com_teamresourceful_bytecodecs: bytecodecs 1.0.2
	com_teamresourceful_yabn: yabn 1.0.3
rightclickharvest: Right Click Harvest 3.2.3+1.19.x-1.20.1-fabric
roughlyenoughitems: Roughly Enough Items 12.0.674
	error_notifier: Error Notifier 1.0.9
roughlyenoughresources: Roughly Enough Resources 2.9.0
scarecrowsterritory: Scarecrows' Territory 1.1.11
servux: Servux 0.1.0
simpleframes: Open Simple Frames 1.1.0
slime: Slime 1.5
supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
supermartijn642corelib: SuperMartijn642's Core Lib 1.1.15
supplementaries: Supplementaries 1.20-2.6.24
	com_github_llamalad7_mixinextras: MixinExtras 0.2.1-beta.2
	mixinsquared: MixinSquared 0.1.1
syncmatica: Syncmatica 1.20.1-0.3.11
travelersbackpack: Traveler's Backpack 1.20.1-9.1.8
trinkets: Trinkets 3.7.1
utilitybelt: Utility Belt 1.3.6+1.20.1
wands: Building Wands 2.6.8-release
whereisit: WhereIsIt 2.0.24+1.20.1
	jackfredlib: JackFredLib 0.5.3+1.20.1
		jackfredlib-base: JackFredLib: Base 1.1.1+1.20.1
		jackfredlib-colour: JackFredLib: Colour 1.0.1+1.20.1
		jackfredlib-extracommandsourcedata: JackFredLib: Extra Command Source Data 1.0.1+1.20.1
		jackfredlib-lying: JackFredLib: Lying 0.3.1+1.20.1
wildlife: Wildlife 1.19.2-2.2
wwoo: William Wythers' Overhauled Overworld 2.0.0
xaerominimap: Xaero's Minimap 23.8.4
xaeroworldmap: Xaero's World Map 1.36.0
yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
	com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
	com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
	com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
	com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
	com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
	com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
	org_quiltmc_parsers_gson: gson 0.2.1
	org_quiltmc_parsers_json: json 0.2.1
yosbr: YOSBR 0.1.2
yungsapi: YUNG's API 1.20-Fabric-4.0.2
	org_javassist_javassist: javassist 3.29.2-GA
yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
yungsextras: YUNG's Extras 1.20-Fabric-4.0.3

**Comment by Dyvinia** [comment]
I'm having this as well. entire contraptions end up getting deleted when this happens

my version of the error:
```
java.lang.IllegalArgumentException: Transfer variant may not be blank.
        at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlank(StoragePreconditions.java:40) ~[quilted-fabric-transfer-api-v1-7.4.00.90.0-1.20.1.i0:0/:?]
        at net.fabricmc.fabric.api.transfer.v1.storage.StoragePreconditions.notBlankNotNegative(StoragePreconditions.java:59) ~[quilted-fabric-transfer-api-v1-7.4.00.90.0-1.20.1.i0:0/:?]
        at net.fabricmc.fabric.api.transfer.v1.item.base.SingleStackStorage.insert(SingleStackStorage.java:109) ~[quilted-fabric-transfer-api-v1-7.4.00.90.0-1.20.1.i0:0/:?]
        at net.fabricmc.fabric.impl.transfer.item.InventorySlotWrapper.insert(InventorySlotWrapper.java:82) ~[quilted-fabric-transfer-api-v1-7.4.00.90.0-1.20.1.i0:0/:?]
        at net.fabricmc.fabric.impl.transfer.item.InventorySlotWrapper.insert(InventorySlotWrapper.java:41) ~[quilted-fabric-transfer-api-v1-7.4.00.90.0-1.20.1.i0:0/:?]
        at net.fabricmc.fabric.api.transfer.v1.storage.base.CombinedStorage.insert(CombinedStorage.java:68) ~[quilted-fabric-transfer-api-v1-7.4.00.90.0-1.20.1.i0:0/:?]
        at com.simibubi.create.content.contraptions.MountedStorage.addStorageToWorld(MountedStorage.java:171) ~[create-0.5.1-d-build.5mc1.20.1.i0:0/:?]
        at com.simibubi.create.content.contraptions.MountedStorageManager.addStorageToWorld(MountedStorageManager.java:176) ~[create-0.5.1-d-build.5mc1.20.1.i0:0/:?]
        at com.simibubi.create.content.contraptions.Contraption.addBlocksToWorld(Contraption.java:1110) ~[create-0.5.1-d-build.5mc1.20.1.i0:0/:?]
        at com.simibubi.create.content.contraptions.AbstractContraptionEntity.disassemble(AbstractContraptionEntity.java:667) ~[create-0.5.1-d-build.5mc1.20.1.i0:0/:?]
        at com.simibubi.create.content.contraptions.OrientedContraptionEntity.method_5848(OrientedContraptionEntity.java:156) ~[create-0.5.1-d-build.5mc1.20.1.i0:0/:?]
        at net.minecraft.class_1297.method_5772(class_1297.java:2138) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_1688.method_5643(class_1688.java:222) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_1657.method_7324(class_1657.java:1263) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_3222.method_7324(class_3222.java:1491) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_3244$1.method_34218(class_3244.java:1610) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_2824$1.method_34213(class_2824.java:166) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_2824.method_34209(class_2824.java:66) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_3244.method_12062(class_3244.java:1571) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_2824.method_12251(class_2824.java:53) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_2824.method_11054(class_2824.java:13) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[minecraft-1.20.1.i0:0/:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[minecraft-1.20.1.i0:0/:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]```
