### ISSUE TITLE
Create sodium fix crash at launch - 1.20.1 fabric - create sodium fix

### ISSUE THREAD

**Issue by njeudy** [EthanRStokes/Create#29]
### Describe the Bug

Hello, I start building a modpack for my futur server, and wish to have:
- Conquest reforged
- Cobblemon
- Create

I'm using iris and sodium on my computer so try to add create sodium fix and my game does not start:

```
[05/03/2024 10:02:12 AM] Description: Initializing game
[05/03/2024 10:02:12 AM] 
[05/03/2024 10:02:12 AM] java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'create'!
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
[05/03/2024 10:02:12 AM] 	at net.minecraft.class_310.<init>(class_310.java:458)
[05/03/2024 10:02:12 AM] 	at net.minecraft.client.main.Main.main(Main.java:211)
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[05/03/2024 10:02:12 AM] Caused by: java.lang.NoClassDefFoundError: io/github/fabricators_of_create/porting_lib/entity/ExtraSpawnDataEntity
[05/03/2024 10:02:12 AM] 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[05/03/2024 10:02:12 AM] 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[05/03/2024 10:02:12 AM] 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[05/03/2024 10:02:12 AM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[05/03/2024 10:02:12 AM] 	at com.simibubi.create.AllBlocks.<clinit>(AllBlocks.java:1282)
[05/03/2024 10:02:12 AM] 	at com.simibubi.create.Create.onInitialize(Create.java:104)
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
[05/03/2024 10:02:12 AM] 	... 6 more
[05/03/2024 10:02:12 AM] Caused by: java.lang.ClassNotFoundException: io.github.fabricators_of_create.porting_lib.entity.ExtraSpawnDataEntity
[05/03/2024 10:02:12 AM] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
[05/03/2024 10:02:12 AM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
[05/03/2024 10:02:12 AM] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
[05/03/2024 10:02:12 AM] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[05/03/2024 10:02:12 AM] 	... 17 more
```
If I remove create sodium fix mod, all is ok .. 

### Reproduction Steps

1. download 1.20.1 modpack https://modrinth.com/modpack/besacraft_1722
2. add create sodium fix
3. start :)
...

### Expected Result

Minecraft is starting et can joind serveur / local world

### Operating System

Window 11

### Mod Version

0.5.1d

### Minecraft Version

1.20.1

### Other Mods

- Conquest reforged
- Cobblemon
- FTB mods

**Comment by EthanRStokes** [comment]
use create fabric.
